### ISSUE TITLE
flutter_custom_devices.json doesn't seem to be read

### ISSUE THREAD

**Issue by Tom3652** [sony/flutter-elinux#107]
Hello ! 

Thank you for making this package. I am trying to run `flutter-elinux devices` to see my external linux device by `ping` so i have created the files as requested here : https://github.com/sony/flutter-elinux/wiki/Remote-target-devices 

However the device is never found. 
Instead, i see in my `~/` directory a file named : `flutter_custom_devices.json.save` that contains the initial configuration for custom devices : 

<img width="780" alt="Capture d’écran 2022-08-09 à 14 05 20" src="https://user-images.githubusercontent.com/32631467/183642816-c642db96-20ce-4a2c-9185-7868612d1751.png">

<img width="653" alt="Capture d’écran 2022-08-09 à 14 05 39" src="https://user-images.githubusercontent.com/32631467/183642873-328d91bf-29a8-4278-9441-fc51d8f5a7f9.png">

What did i do wrong please ? Or maybe it is a real bug ?

**Comment by HidenoriMatsubayashi** [comment]
The file name should be .flutter_custom_devices.json.

**Comment by Tom3652** [comment]
I feel stupid, thank you so much.

**Comment by freshteapot-rm** [comment]
If you got here and it wasn't working.

Re-run the doctor and pay attention to the part that talks about missing entries into $PATH

```
[!] Flutter (Channel [user-branch], 3.24.3, on macOS 14.4 23E214 darwin-arm64, locale en-GB)
    ! Flutter version 3.24.3 on channel [user-branch] at /Users/XXX/git/flutter-elinux/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/setup.
    ! The flutter binary is not on your path. Consider adding /Users/XXX/git/flutter-elinux/flutter/bin to your path.
    ! The dart binary is not on your path. Consider adding /Users/XXX/git/flutter-elinux/flutter/bin to your path.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
```

- I first in the terminal grabbed the path and pasted into an editor
- Removed reference to flutter
- Added the two suggested paths under flutter-elinux

Only after doing this, did the device work.

And if you are on mac, open the custom config and look for the block for "ping".

I had to change "-w" to "-W" UPPER CASE.
