### ISSUE TITLE
how to build flutter-elinux binary

### ISSUE THREAD

**Issue by seanchann** [sony/flutter-elinux#112]
we need a document for the developer.  the current project is not a  normal flutter project.  using `flutter build linux`  does not work for me

**Comment by HidenoriMatsubayashi** [comment]
Please check https://github.com/sony/flutter-elinux/wiki

**Comment by seanchann** [comment]
sorry, I may have confused you. I modify the file in the dir `flutter-elinux/lib`. so need to rebuild flutter-elinux binary.  the wiki is just given a cp command

**Comment by HidenoriMatsubayashi** [comment]
Sorry, I'm not sure what your question is.

**Comment by seanchann** [comment]
just see 
![image](https://user-images.githubusercontent.com/7686068/184268698-707da3ff-f359-458b-9a9b-7a9084460997.png)
add a `--verbose`  with  cmake --build. so need manual build flutter-elinux

**Comment by HidenoriMatsubayashi** [comment]
Please see https://github.com/sony/flutter-elinux/wiki/Building-flutter-apps#3-cross-building-from-x64-to-arm64

**Comment by HidenoriMatsubayashi** [comment]
Please use the latest version and try `flutter-elinux build elinux`

**Comment by seanchann** [comment]
in `flutter-elinux` project. (recompile binary of `flutter-elinux`)

call  `flutter-elinux-bak build elinux bin/flutter_elinux.dart` not work 


```
Flutter 3.0.5 • channel unknown • unknown source
Framework • revision f1875d570e (4 weeks ago) • 2022-07-13 11:24:16 -0700
Engine • revision e85ea0e79c
Tools • Dart 2.17.6 • DevTools 2.12.2

Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

This project is not configured for eLinux.
To fix this problem, create a new project by running `flutter-elinux create <app-dir>`.
```

**Comment by seanchann** [comment]
I made a mistake, directly modifying lib/*.dart in flutter-elinux will take effect directly. flutter-elinux is a shell script in bin dir, no need to generate or compiler and so on

**Comment by hoangtoi25** [comment]
I have same issue. How to resolve this issue @seanchann

**Comment by hoangtoi25** [comment]
> Please use the latest version and try `flutter-elinux build elinux`

![image](https://github.com/user-attachments/assets/bf0f39cc-e9b7-4049-964b-ce3d69d6a336)
