### ISSUE TITLE
[Question]Complete process to run on rpi4

### ISSUE THREAD

**Issue by mantreshkhurana** [sony/flutter-elinux#117]
Hi there, I am developing an app that I want to run on rpi4 on boot using embedded linux but I am new in this field, can anyone tell me the process from building and using flutter elinux to run my app on rpi4 using embedded linux(how to install embedded linux on rpi4 to run my flutter app?)

**Comment by HidenoriMatsubayashi** [comment]
Please check https://github.com/sony/flutter-elinux/wiki.
