### ISSUE TITLE
cross compile error

### ISSUE THREAD

**Issue by fayfive** [sony/flutter-elinux#120]
At the end of `flutter-elinux build elinux --target-arch=arm64 --target-sysroot=/mnt/nfs/` ,it shows that
```
/opt/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-ld: warning: libdl.so.2, needed by
/home/alfred/working/da/elinux/elinux/flutter/ephemeral/libflutter_engine.so, not found (try using -rpath or -rpath-link)
```
ubuntu 22.04 
cmake version 3.22.1
Ubuntu clang version 14.0.0-1ubuntu1

**Comment by fayfive** [comment]
I have to docker and `apt install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu`
I don't know why

**Comment by HidenoriMatsubayashi** [comment]
In general, it's not easy to advice to issues of cross-buildings because we don't know your environment.
