### ISSUE TITLE
No devices found with name or id matching 'elinux'

### ISSUE THREAD

**Issue by suyulin** [sony/flutter-elinux#13]
hi，
![image](https://user-images.githubusercontent.com/6275411/126442282-1975e92c-8248-4630-b5b7-9ce32d824aae.png)

**Comment by HidenoriMatsubayashi** [comment]
Than you for your comment. I've just committed. Could you do the following command?

```Shell
$ flutter-elinux doctor
```

**Comment by HidenoriMatsubayashi** [comment]
And then, could you try the following?

```Shell
$ flutter-elinux create sample
$ cd sample
$ flutter-elinux run -rd elinux
```

**Comment by suyulin** [comment]
> Than you for your comment. I've just committed. Could you do the following command?
> 
> ```shell
> $ flutter-elinux doctor
> ```

i run project on arm64 , not support.
