### ISSUE TITLE
Failed to connect to the Wayland display

### ISSUE THREAD

**Issue by 1056824847** [sony/flutter-elinux#132]
<img width="855" alt="image" src="https://user-images.githubusercontent.com/44287872/188284349-9d7ea357-f8c8-4e1f-b5fb-165f0e235b23.png">
<img width="722" alt="image" src="https://user-images.githubusercontent.com/44287872/188284382-2189f6af-a081-433d-9ad9-ed6170d3ad8f.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/44287872/188284408-536e9b67-9330-4411-8eb0-6c518e967b81.png">

**Comment by HidenoriMatsubayashi** [comment]
It looks like you are using Ubuntu 20.04, but did you launch Wayland compositors like Weston?

**Comment by HidenoriMatsubayashi** [comment]
I'll close the issue as no responses.
