### ISSUE TITLE
[Question] Should keyboard show up under X11 ?

### ISSUE THREAD

**Issue by Tom3652** [sony/flutter-elinux#133]
Hello ! 

Is the soft keyboard something that should be implemented by this plugin or i should install some packages myself ? 
When i touch a `TextField` in my flutter app on my debian 11 under Openbox - X11, no keyboard is showing up.

Note : I am asking here because i saw you made some changes to support it for Wayland in another issue. 
Thanks a lot in advance !

**Comment by HidenoriMatsubayashi** [comment]
Basically, X11 backend support is incomplete.

see also: https://github.com/sony/flutter-embedded-linux/issues

**Comment by Tom3652** [comment]
Oh alright thanks, i will try to install GNOME to use Wayland. 

Weston only works in a nested compositor as far as i understood so it's useless...

**Comment by Tom3652** [comment]
Well my device has not enough disk space for GNOME unfortunately, it requires 2Gb and i have 1Gb... 

Can you tell me please if it's useful that i make an issue in the official flutter repo about it ? As they should support it (not especially on embedded devices i mean, simply on linux under x11) ?

**Comment by HidenoriMatsubayashi** [comment]
> Can you tell me please if it's useful that i make an issue in the official flutter repo about it ?

What do you mean?

**Comment by Tom3652** [comment]
I have my answer, i have managed to run my app compiled with `flutter` and not `flutter-elinux`, the keyboard isn't showing either.

I have installed the `onboard` package to display a virtual keyboard (by forcing it) and it's writing in the `TextField` (but it's really ugly). 

My next move will be to trigger a virtual keyboard `onTap` on the `TextField` then...

**Comment by Tom3652** [comment]
I have ended up coding my own keyboard using `GridViews`
