### ISSUE TITLE
Add support for multiple potential dri cards.

### ISSUE THREAD

**Issue by callumhopkinsdev** [sony/flutter-elinux#143]
Currently using the DRM backend you can only select a single card via `FLUTTER_DRM_DEVICE`. However, on the Raspberry Pi 4 the vc4 driver can randomly select either `/dev/dri/card0` or `/dev/dri/card1` at boot time. 

Most other DRM based applications iterate through all of the devices in the `/dev/dri/` directory and attempt to open each one until they are successful. 

It would be great if either the `FLUTTER_DRM_DEVICE` variable allowed for a comma seperated list of devices to attempt to open, or if by default the DRM backend would attempt to open every device until one is successful.

**Comment by HidenoriMatsubayashi** [comment]
Thanks for creating the issue.

> However, on the Raspberry Pi 4 the vc4 driver can randomly select either /dev/dri/card0 or /dev/dri/card1 at boot time.

Really? Where can I find that information?

**Comment by callumhopkinsdev** [comment]
On this thread, a few posts down you can find a quote directly from one of the engineers. 

https://forums.raspberrypi.com/viewtopic.php?t=307392&sid=0519efbedbfc3f01ff2dbf41547ff41e

Moreover, I've experienced this behaviour personally when working on a C# GUI toolkit (Avalonia)

**Comment by HidenoriMatsubayashi** [comment]
Thanks for the information. I'll implement this feature.

**Comment by HidenoriMatsubayashi** [comment]
I created https://github.com/sony/flutter-embedded-linux/pull/295

**Comment by HidenoriMatsubayashi** [comment]
@callumhopkinsdev The change will be included in a next release (flutter 3.3.6?). If you want to add more improvements, please create a PR. Thanks.

**Comment by callumhopkinsdev** [comment]
Awesome, thanks @HidenoriMatsubayashi!
