### ISSUE TITLE
Not running in AOT mode but could not resolve the kernel binary.

### ISSUE THREAD

**Issue by Lynchez** [sony/flutter-elinux#151]
run with x11 
`flutter-elinux run -d elinux-x11`
its work but when i try to get 
`flutter-elinux build elinux --debug --target-backend-type=x11`
 it gives this error

`embedder.cc (1218): 'FlutterEngineInitialize' returned 'kInvalidArguments'. Not running in AOT mode but could not resolve the kernel binary.
[ERROR][RunWithEntrypoint(255)] Failed to start Flutter engine: error 2
Failed to create view controller.
`

flutter-elinux doctor seems fine. Device is Jetson nano jetpack 4.6

the other backend types gives error too /dev/dri/card0
Failed to connect to the Wayland display.

**Comment by HidenoriMatsubayashi** [comment]
>run with x11 its work but when i try to get build
>flutter-elinux build elinux --debug --target-backend-type=x11
>it gives this error

I'm not sure, that is a command to build (not to run). Can you please share whole steps and logs?

**Comment by Lynchez** [comment]
I can run only with `flutter-elinux run -d elinux-x11` the other running options gives error. But when i try to get build with this command `flutter-elinux build elinux --debug --target-backend-type=x11` it gives error too.

`
embedder.cc (1218): 'FlutterEngineInitialize' returned 'kInvalidArguments'. Not running in AOT mode but could not resolve the kernel binary. [ERROR][RunWithEntrypoint(255)] Failed to start Flutter engine: error 2 Failed to create view controller.
`

**Comment by HidenoriMatsubayashi** [comment]
Sorry for the late response. I confirmed 'flutter-elinux build elinux --debug --target-backend-type=x11' worked fine on Raspberry Pi4. Please try the latest version.
