### ISSUE TITLE
Pressing the 'q' key does not terminate the application on the remote device

### ISSUE THREAD

**Issue by makotosato-at** [sony/flutter-elinux#157]
Hello

I am trying the following commands on host pc(x86):
```
$ flutter-elinux run -d target_device_arm64
(snip)

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on eLinux is available at:
http://127.0.0.1:37541/kkd7NI14PDo=/
The Flutter DevTools debugger and profiler on eLinux is available at:
http://127.0.0.1:9100?uri=http://127.0.0.1:37541/kkd7NI14PDo=/
```
The application starts correctly on the remote target device(arm64).
But, pressing the q key does not terminate the application.

How do I terminate an application on a remote target device?

**Comment by HidenoriMatsubayashi** [comment]
Although this is the known issue, there is currently no resolution.

**Comment by makotosato-at** [comment]
Thank you for your reply.
Well noted.

**Comment by HidenoriMatsubayashi** [comment]
To address this issue, I made a change that adds `stopApp` command to custom_devices.json. Thanks.

**Comment by HidenoriMatsubayashi** [comment]
Updated https://github.com/sony/flutter-elinux/wiki/Remote-target-devices#create-flutter_custom_devicesjson.
