### ISSUE TITLE
Can I run the elinux flutter app without weston

### ISSUE THREAD

**Issue by fayfive** [sony/flutter-elinux#169]
`flutter-elinux build elinux --target-backend-type=eglstream --target-arch=arm64  --target-compiler-triple=aarch64-linux-gnu --target-sysroot=<Absolute_path_to>/ubuntu18-arm64-sysroot`

I find that I can't run it without `weston`. How can I do that?

**Comment by HidenoriMatsubayashi** [comment]
I'm not sure what you want to do. eglstream doesn't work on Weston.

**Comment by fayfive** [comment]
> I'm not sure what you want to do. eglstream doesn't work on Weston.

eglstream works well on Weston. But I can not run weston on rk3328.
