### ISSUE TITLE
Weird display issues under Raspi4 Debian using Wayland(Weston 9.0.0)

### ISSUE THREAD

**Issue by m-theis** [sony/flutter-elinux#176]
Hey everyone,

I am experiencing a rather weird behavior when running the sample-app
on a raspberry pi 4 b using the Offical OS (Bullseye) Wayland with Weston v9

![2023-04-04-180805_800x480_scrot](https://user-images.githubusercontent.com/7016031/229867061-656e7a4d-b76f-4812-8071-b9a54cb49a15.png)

The weird thing is, this is not happening when I am running the sample app trough x11. Does anyone maybe have any suggestions what that could be? I am still running in the dark at that moment

**Comment by HidenoriMatsubayashi** [comment]
I guess you are using a quite small size of display. Is that correct? The default size is 1280 x 720. Please use `-f` option or `-w`/`-h` options.

**Comment by m-theis** [comment]
Hi Hidenori,

thanks for checking it. Yes I think it is a bug, but I don't really know yet what is happening, since it is working when using x11 on the exact same screen size. I will follow up as soon as I had a chance to investigate further what is happening here. In case I can provide any logs or further details let me know @HidenoriMatsubayashi .

**Comment by HidenoriMatsubayashi** [comment]
Thanks. I've fixed this issue. The change will be included in the next release.
