### ISSUE TITLE
Rotation issue

### ISSUE THREAD

**Issue by thomtomdup** [sony/flutter-elinux#181]
Hello.

Since 3.7 version i have a problem on Yocto projhect imx8 with wayland. When i want to rotate with parameter -r 90 half or all screen is freezed. It unfreeze when i touch many time the screen.

Have you seen this issue or not ?

Thank you,
Regards

**Comment by HidenoriMatsubayashi** [comment]
Specifically, what version happens this issue? Also, have you tried the latest version?

**Comment by thomtomdup** [comment]
The version is the last ( i have updated version today ) and did tests but same issue.

**Comment by HidenoriMatsubayashi** [comment]
rotation option (`-r`) may not be working properly in the first place. Are you using 90 or 270 degree rotation?

**Comment by thomtomdup** [comment]
Hello.
I tested it without -r and all work good.

**Comment by HidenoriMatsubayashi** [comment]
Can you try to use Sway or other Wayland compositor instead of Weston?

**Comment by HidenoriMatsubayashi** [comment]
I guess this issue is related to https://github.com/sony/flutter-embedded-linux/issues/349, which has already fixed.
