### ISSUE TITLE
[Request] Update documentation with debug instruction for flutter-elinux tool

### ISSUE THREAD

**Issue by psstoyanov** [sony/flutter-elinux#185]
Having a section like the one in Tizen's docs will be great: https://github.com/flutter-tizen/flutter-tizen/wiki/Debugging-the-flutter%E2%80%91tizen-tool

It could allow for easier contributions as well

**Comment by psstoyanov** [comment]
Note:
I'm still not sure how to use the debugger for other tasks but at least regenerating `flutter-elinux` is an option :smile:

**Comment by HidenoriMatsubayashi** [comment]
Closing as I created https://github.com/sony/flutter-elinux/wiki/Debugging-flutter-elinux-tool
