### ISSUE TITLE
Artifacts download failure

### ISSUE THREAD

**Issue by Li-00** [sony/flutter-elinux#191]
![image](https://github.com/sony/flutter-elinux/assets/71139000/6e8be6e0-6616-4322-bc36-676b158ecdb4)

![image](https://github.com/sony/flutter-elinux/assets/71139000/2b2d988d-5bfb-47b6-9f3d-6bd4bead1631)

![image](https://github.com/sony/flutter-elinux/assets/71139000/44943888-c9de-4d8e-9b7b-53d92af7559c)
![image](https://github.com/sony/flutter-elinux/assets/71139000/cfb89b0a-e219-4e6f-82f7-1e24541a4145)

![image](https://github.com/sony/flutter-elinux/assets/71139000/260b0802-dd97-4639-bcf0-36e6673ff914)

I can ping github.com but run or build demo Downloading elinux-common tools faild ， don's know how to fix

**Comment by HidenoriMatsubayashi** [comment]
I guess this is your network environment issue. Are you accessing from China? Can you download https://github.com/sony/flutter-embedded-linux/releases/tag/cdbeda788a manually?

See also https://github.com/sony/flutter-elinux/issues/140#issuecomment-1477907892

**Comment by Li-00** [comment]
> 

yes, I'm in china run this demo,and i download release so put in  cache path
![image](https://github.com/sony/flutter-elinux/assets/71139000/3c1ffa11-5a20-4784-920a-f5e19b9dc1f2)

Is there any other possibility? thank you for your answer.

**Comment by Li-00** [comment]
My computer can access github through the proxy without hindrance, but the embedded device cannot use the proxy, and I tried the flutter-elinux precache --elinux command, and the problem was the same, stuck in Downloading elinux-common tools for a long time...

**Comment by HidenoriMatsubayashi** [comment]
I created a new PR to add this use case.

1. Download the elinux artifacts from https://github.com/sony/flutter-embedded-linux/releases
2. export ELINUX_ENGINE_BASE_LOCAL_DIRECTORY=<path_to_directory_of_downloaded_artifacts>
3. run flutter commands

**Comment by HidenoriMatsubayashi** [comment]
Closing.

**Comment by HidenoriMatsubayashi** [comment]
Created https://github.com/sony/flutter-elinux/wiki/Use-local-elinux-artifacts-without-downloading-from-GitHub.

**Comment by Li-00** [comment]
With the latest update, you can set up the proxy by configuring /etc/profile

First of all
vim /etc/profile
Then, add it to the file 
http_proxy=http://ip:port
https_proxy=https://ip:port
export http_proxy
export https_proxy
Finally, refresh the file
source /etc/profile


But when I try to run the project after building the project, it prompts Failed to create view controller, my board is rk3568 Debain10 aarch64, and I'm following https://github.com/sony/flutter-elinux/issues/121 to try to solve it
