### ISSUE TITLE
flutter_tools.stamp version check in shared.sh always fails

### ISSUE THREAD

**Issue by m4dm4x** [sony/flutter-elinux#195]
### Hello,

in the file ` bin/internal/shared.sh` the check 
```
if [[ ! -f "$stamp_path" || "$version" != "$(cat "$stamp_path")" ]]; then
```
alwais fails beause the generated stampfile contains the revision **and** the tool arguments. This means on **every** run the script will try a tool update. The stampfile is generated by Flutter file `flutter/bin/internal/shared.sh`:
```
local compilekey="$revision:$FLUTTER_TOOL_ARGS"
...
echo "$compilekey" > "$STAMP_PATH"
```

See commit https://github.com/flutter/flutter/pull/94951/commits/7f47e1d09f8f06420738b35eca7fbea15e27330e

**Comment by HidenoriMatsubayashi** [comment]
Thank you for creating an issue!
