### ISSUE TITLE
Unification of Runtime Libraries

### ISSUE THREAD

**Issue by alberrizwan** [sony/flutter-elinux#197]
I need to create a runtime container for Flutter applications. My goal is to minimize the final image footprint as much as possible. Although I have already managed to reduce the size significantly, I still want to further optimize it. To achieve this, I plan to unify the following Flutter runtime libraries: elinux-arm64-debug, elinux-arm64-profile, and elinux-arm64-release. I would greatly appreciate any suggestions or input you may have on this matter.
<img width="528" alt="Screenshot 2023-07-28 at 9 08 03 PM" src="https://github.com/sony/flutter-elinux/assets/140834605/0f044e53-cd0d-4544-a810-9f09625b0b61">

**Comment by HidenoriMatsubayashi** [comment]
> I plan to unify the following Flutter runtime libraries: elinux-arm64-debug, elinux-arm64-profile, and elinux-arm64-release.

Basically, there are all necessary. But if you don't need debug and profile flavors, elinux-arm64-debug and elinux-arm64-profile can be deleted. Naturally, in this case, flutter-elinux commands with debug/profile won't work.

**Comment by HidenoriMatsubayashi** [comment]
Also, if there are unnecessary display backends that you don't support, their .so files can be deleted.

libflutter_elinux_eglstream.so for EGLStream
libflutter_elinux_gbm.so for GBM
libflutter_elinux_wayland.so for Wayland
libflutter_elinux_x11.so for X11

**Comment by HidenoriMatsubayashi** [comment]
Closing.
