### ISSUE TITLE
Is there soft keyboard and IME support for the touch screen devices? 

### ISSUE THREAD

**Issue by xixixihaha** [sony/flutter-elinux#198]
Under embedded Linux environment, looks like there is no input method support. Is there any solution available?

Thanks

**Comment by HidenoriMatsubayashi** [comment]
flutter-elinux supports both physical and virtual keyboards.

**Comment by HidenoriMatsubayashi** [comment]
It is not the responsibility of flutter to display the virtual keyboard itself. That needs to be handled on the window manager side.
