### ISSUE TITLE
Mouse / Touch input support for DRM-GBM Backend 

### ISSUE THREAD

**Issue by Arna-Maity** [sony/flutter-elinux#217]
Are mouse and touch inputs supported for DRM-GBM Backends?

**Comment by HidenoriMatsubayashi** [comment]
Yes. Thanks.

**Comment by Arna-Maity** [comment]
@HidenoriMatsubayashi Actually I was unable to use the mouse/trackpad using the GBM backend on an x64 PC.

Also, is there a way to terminate the app once it is already running?

**Comment by HidenoriMatsubayashi** [comment]
Does an user who you are using for running your flutter app have a permission to access input devices(/dev/input/xxx)?

> Also, is there a way to terminate the app once it is already running?

This is a general question. Please google it.

**Comment by Arna-Maity** [comment]
> Does an user who you are using for running your flutter app have a permission to access input devices(/dev/input/xxx)?

My user account does have **RW** access, does it also need the **execute (X)** bit set?

![Inputs](https://github.com/sony/flutter-elinux/assets/32426434/a53e7682-7ac2-4f21-90b3-68427bcae7f8)

> This is a general question. Please google it.

Tried most of the general ways to close the application but the issue is once the application is opened (in **DRM/GBM** mode), it doesn't seem to respond to any kind of user input. It was also not possible to switch to a different **tty** session to kill the process. Maybe I suppose this is related to my inputs not working when the application is running **in DRM/GBM** mode.

**Comment by talksik** [comment]
@Arna-Maity were you able to change the permissions and get this working?

@HidenoriMatsubayashi I believe a post like this should be re-opened if the issue is not resolved.

**Comment by Arna-Maity** [comment]
> were you able to change the permissions and get this working?

Not yet. Still facing this issue.

**Comment by talksik** [comment]
@Arna-Maity please let me know when you have changed the permissions with `chmod` and tested.

**Comment by Arna-Maity** [comment]
So I tried giving **RW** permissions to the **Others** field of all the input devices `/dev/input/event*`, `/dev/input/mouse*` and `/dev/input/mice` using the following:

```
sudo chmod 666 /dev/input/event* /dev/input/mouse* /dev/input/mice
```

That seemed to do the job.

Thanks, @talksik  @HidenoriMatsubayashi .

**Comment by talksik** [comment]
Perfect thank you for closing the loop!
