### ISSUE TITLE
No title bar for the built project

### ISSUE THREAD

**Issue by CodingTurtle2** [sony/flutter-elinux#257]
If you run a normal Flutter app in Wayland with `flutter-elinux run`, it has a title bar, but if you then build the app, the title bar disappears:

![grafik](https://github.com/sony/flutter-elinux/assets/104490184/5ffc57cc-a6fb-4b84-9796-65cfc1a0b70f)

**Comment by HidenoriMatsubayashi** [comment]
Please see https://github.com/sony/flutter-embedded-linux/wiki/How-to-run-Flutter-apps#command-options

Closing.
