### ISSUE TITLE
flutter-elinux with existing projects

### ISSUE THREAD

**Issue by Nagendra-Bankupalli** [sony/flutter-elinux#32]
Hello @HidenoriMatsubayashi 

flutter-elinux works with project created as below, if I would like to use it for existing flutter projects ,how can I achieve it ?
do we have any configuration option ?
flutter-elinux create <your_app_project_name>   => works

while trying to build existing flutter apps, end up with 
Non-nullable instance field 'cccc' must be initialized, (flutter-elinux analyze)

**Comment by HidenoriMatsubayashi** [comment]
In this case, we need to create or copy an elinux directory. Please do the following:
```Shell
$ cd <path_to_your_existing flutter_project>
$ flutter-elinux create .
``

**Comment by Nagendra-Bankupalli** [comment]
Yes, it works ! thank you
