### ISSUE TITLE
Issue in Rapberry Pi (aarch64)

### ISSUE THREAD

**Issue by thomtomdup** [sony/flutter-elinux#78]
Hello.

I tried to install flutter-elinux in a Raspberry Pi (aarch64) all work good but it's freeze at this stage :
Building flutter tool...

Do you know what is the issue ?
I tried to find a solution in web but found nothing.
Thank you very much for yiour help.
Regards

**Comment by HidenoriMatsubayashi** [comment]
Thank you for your comment. I guess it just takes a while to build.
