### ISSUE TITLE
Building flutter app with Yocto SDK.

### ISSUE THREAD

**Issue by thomtomdup** [sony/flutter-elinux#85]
Hello.
Do you have a documentation or wiki explication on how building app with Yocto SDK or buildroot ?
The same than this :

https://github.com/sony/flutter-elinux/wiki/Building-flutter-apps

I used actually this process (Docker + QEMU) it work perfectly but I need to build with Yocto SDK.

Thank you,
Regards.

**Comment by HidenoriMatsubayashi** [comment]
@thomtomdup 

Sorry for the late reply. Could you check https://github.com/sony/flutter-embedded-linux/issues/4#issuecomment-1090157925 and try it?

**Comment by HidenoriMatsubayashi** [comment]
Also, please see https://github.com/sony/flutter-elinux/wiki/Building-flutter-apps#case-2-use-yocto-sdk.
